[package]
name = "advent_of_code"
version = "0.1.0"
authors = ["ajmorton <ajmorton2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.0"
scan_fmt = "0.2.4"